"""Initial schema: weather and commodities

Revision ID: 0bd1892025fc
Revises: 
Create Date: 2026-02-11 16:58:34.849260

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bd1892025fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commodity_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("close_price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commodity_prices")),
    )
    op.create_index(
        op.f("ix_commodity_prices_date"), "commodity_prices", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_commodity_prices_id"), "commodity_prices", ["id"], unique=False
    )
    op.create_table(
        "weather_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("temp_mean", sa.Float(), nullable=False),
        sa.Column("precip_mm", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_metrics")),
    )
    op.create_index(
        op.f("ix_weather_metrics_date"), "weather_metrics", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_weather_metrics_id"), "weather_metrics", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_metrics_id"), table_name="weather_metrics")
    op.drop_index(op.f("ix_weather_metrics_date"), table_name="weather_metrics")
    op.drop_table("weather_metrics")
    op.drop_index(op.f("ix_commodity_prices_id"), table_name="commodity_prices")
    op.drop_index(op.f("ix_commodity_prices_date"), table_name="commodity_prices")
    op.drop_table("commodity_prices")
    # ### end Alembic commands ###
